name: quaze_traefik

services:
  server:
    build:
      context: .
      target: final
    depends_on:
      db:
        condition: service_healthy
    restart: always
    expose:
      - 8080
    networks:
      - traefik
      - internal
    environment:
      - TZ=Europe/Budapest
      - ASPNETCORE_ENVIRONMENT=Docker
    labels:
      - "traefik.http.routers.quaze.rule=Host(`q2.jmrtn.dev`)"
      #- "traefik.http.routers.quaze.entrypoints=websecure"
      - "traefik.http.routers.quaze.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"
  db:
    image: yobasystems/alpine-mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal
    environment:
      - TZ=Europe/Budapest
      - MYSQL_DATABASE=quaze
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_USER=quaze
      - MYSQL_PASSWORD=quaze
    healthcheck:
      test: ['CMD-SHELL', '/usr/bin/mysqladmin ping -u quaze --silent']
      interval: 3s
      retries: 10
      start_period: 2s
volumes:
  db-data:
    driver: local

networks:
  traefik:
    external: true
  internal: