services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8086:8080
    depends_on:
        db:
          condition: service_healthy
    restart: always
    environment:
      - TZ=Europe/Budapest
      - ASPNETCORE_ENVIRONMENT=Docker
  db:
    image: yobasystems/alpine-mariadb
    container_name: mariadb-server
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - TZ=Europe/Budapest
      - MYSQL_DATABASE=quaze
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_USER=quaze
      - MYSQL_PASSWORD=quaze
    expose:
      - "3306"
    healthcheck:
      test: ['CMD-SHELL', '/usr/bin/mysqladmin ping -u quaze --silent']
      interval: 3s
      retries: 10
      start_period: 10s
volumes:
  db-data:
    driver: local