name: quaze_devenv

services:
  db:
    image: yobasystems/alpine-mariadb
    container_name: mariadb-server
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - TZ=Europe/Budapest
      - MYSQL_DATABASE=quaze
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_USER=quaze
      - MYSQL_PASSWORD=quaze
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD-SHELL', '/usr/bin/mysqladmin ping -u quaze --silent']
      interval: 3s
      retries: 10
      start_period: 2s
  phpmyadmin:
    image: phpmyadmin:apache
    restart: always
    ports:
      - 8087:80
    environment:
      - MYSQL_USER=quaze
      - MYSQL_PASSWORD=quaze
      - PMA_HOST=db
volumes:
  db-data:
    driver: local